In [1]:
import pandas as pd
import numpy as np
file = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/module_5_auto.csv"

In [2]:
df= pd.read_csv(file)
df.tail()

Unnamed: 0  Unnamed: 0.1  symboling  normalized-losses   make aspiration  \
196         196           196         -1                 95  volvo        std   
197         197           197         -1                 95  volvo      turbo   
198         198           198         -1                 95  volvo        std   
199         199           199         -1                 95  volvo      turbo   
200         200           200         -1                 95  volvo      turbo   

    num-of-doors body-style drive-wheels engine-location  ...  \
196         four      sedan          rwd           front  ...   
197         four      sedan          rwd           front  ...   
198         four      sedan          rwd           front  ...   
199         four      sedan          rwd           front  ...   
200         four      sedan          rwd           front  ...   

     compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
196                9.5       114.0    5400.0        23           28  16845.0   
197                8.7       160.0    5300.0        19           25  19045.0   
198                8.8       134.0    5500.0        18           23  21485.0   
199               23.0       106.0    4800.0        26           27  22470.0   
200                9.5       114.0    5400.0        19           25  22625.0   

    city-L/100km  horsepower-binned diesel  gas  
196    10.217391             Medium      0    1  
197    12.368421               High      0    1  
198    13.055556             Medium      0    1  
199     9.038462             Medium      1    0  
200    12.368421             Medium      0    1  

[5 rows x 31 columns]

In [9]:
#used to get every numeric data found in the data set
df = df._get_numeric_data()
df.head()

Unnamed: 0  Unnamed: 0.1  symboling  normalized-losses  wheel-base  \
0           0             0          3                122        88.6   
1           1             1          3                122        88.6   
2           2             2          1                122        94.5   
3           3             3          2                164        99.8   
4           4             4          2                164        99.4   

     length     width  height  curb-weight  engine-size  ...  stroke  \
0  0.811148  0.890278    48.8         2548          130  ...    2.68   
1  0.811148  0.890278    48.8         2548          130  ...    2.68   
2  0.822681  0.909722    52.4         2823          152  ...    3.47   
3  0.848630  0.919444    54.3         2337          109  ...    3.40   
4  0.848630  0.922222    54.3         2824          136  ...    3.40   

   compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
0                9.0       111.0    5000.0        21           27  13495.0   
1                9.0       111.0    5000.0        21           27  16500.0   
2                9.0       154.0    5000.0        19           26  16500.0   
3               10.0       102.0    5500.0        24           30  13950.0   
4                8.0       115.0    5500.0        18           22  17450.0   

   city-L/100km  diesel  gas  
0     11.190476       0    1  
1     11.190476       0    1  
2     12.368421       0    1  
3      9.791667       0    1  
4     13.055556       0    1  

[5 rows x 21 columns]

In [5]:
%%capture
! pip install ipywidgets

In [6]:
from IPython.display import display
from IPython.html import widgets 
from IPython.display import display
from ipywidgets import interact, interactive, fixed, interact_manual

C:\Users\efere\anaconda3\lib\site-packages\IPython\html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [7]:
def DistributionPlot(RedFunction, BlueFunction, RedName, BlueName, Title):
    width = 12
    height = 10
    plt.figure(figsize=(width, height))

    ax1 = sns.distplot(RedFunction, hist=False, color="r", label=RedName)
    ax2 = sns.distplot(BlueFunction, hist=False, color="b", label=BlueName, ax=ax1)

    plt.title(Title)
    plt.xlabel('Price (in dollars)')
    plt.ylabel('Proportion of Cars')

    plt.show()
    plt.close()

In [8]:
def PollyPlot(xtrain, xtest, y_train, y_test, lr,poly_transform):
    width = 12
    height = 10
    plt.figure(figsize=(width, height))
    
    
    #training data 
    #testing data 
    # lr:  linear regression object 
    #poly_transform:  polynomial transformation object 
 
    xmax=max([xtrain.values.max(), xtest.values.max()])

    xmin=min([xtrain.values.min(), xtest.values.min()])

    x=np.arange(xmin, xmax, 0.1)


    plt.plot(xtrain, y_train, 'ro', label='Training Data')
    plt.plot(xtest, y_test, 'go', label='Test Data')
    plt.plot(x, lr.predict(poly_transform.fit_transform(x.reshape(-1, 1))), label='Predicted Function')
    plt.ylim([-10000, 60000])
    plt.ylabel('Price')
    plt.legend()

In [21]:
from sklearn.model_selection import train_test_split
x_data=df.drop('price', axis=1)
y_data =df['price']
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.4, random_state=0)

In [22]:
print(x_train.shape[0], x_test.shape[0])

120 81


In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
#always fit using the train model
lm = LinearRegression()
lm.fit(x_train[['horsepower']], y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
#test data
lm.score(x_test[['horsepower']], y_test)

0.7139364665406973

In [26]:
#train data
lm.score(x_train[['horsepower']], y_train)

0.5754067463583004

In [27]:
from sklearn.model_selection import cross_val_score

In [29]:
#cross validation score
Rcross = cross_val_score(lm, x_data[['horsepower']], y_data, cv=4)
Rcross

array([0.7746232 , 0.51716687, 0.74785353, 0.04839605])

In [31]:
d = Rcross.mean()
e = Rcross.std()
print("The mean of the folds are: ", d, " and the standard deviation is: ", e)

The mean of the folds are:  0.522009915042119  and the standard deviation is:  0.29118394447560286


In [32]:
from sklearn.model_selection import cross_val_predict

In [34]:
Pcross = cross_val_predict(lm, x_data[['horsepower']], y_data, cv=4)
Pcross[0:5]

array([14141.63807508, 14141.63807508, 20814.29423473, 12745.03562306,
       14762.35027598])

In [38]:
lr= LinearRegression()
lr.fit(x_train[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']], y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [39]:
y1=lr.predict(x_train[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']])
y1[0:5]

array([38237.3225152 ,  8757.67570728, 16832.43125207, 16093.28264058,
       14757.89820098])